plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.mhy.appupdate'
    compileSdk 34

    defaultConfig {
        applicationId "com.mhy.appupdate"
        minSdk 16
        targetSdk 34
        versionCode 5
        versionName "1.5"

    }
    signingConfigs {
        create("release") {
            storeFile file("D:\\ApkKey\\55.jks")
            storePassword "201055"
            keyAlias "55"
            keyPassword "201055"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.getByName("release")
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.getByName("release")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.okhttp3.okhttp
    implementation libs.com.google.gson
    implementation 'com.mhy:appupdate:0.0.1'
//    implementation project(":appupdate")
}