plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.mhy.appupdate'
    compileSdk 34

    defaultConfig {
        applicationId "com.mhy.appupdate"
        minSdk 16
        targetSdk 34
        versionCode 7
        versionName "1.7"
        // 只保留中文
        resConfigs "zh", "en"
    }

    //获取local.properties配置文件
    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    def MY_STORE_FILE = localProperties.getProperty('MY_STORE_FILE')
    def MY_STORE_PWD = localProperties.getProperty('MY_STORE_PWD')
    def MY_KEY_ALIAS = localProperties.getProperty('MY_KEY_ALIAS')
    def MY_KEY_PWD = localProperties.getProperty('MY_KEY_PWD')

    signingConfigs {
        create("release") {
            storeFile file(MY_STORE_FILE)
            storePassword MY_STORE_PWD
            keyAlias MY_KEY_ALIAS
            keyPassword MY_KEY_PWD
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.getByName("release")
            minifyEnabled true
            // 移除无用的资源
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.getByName("release")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.okhttp3.okhttp
    implementation libs.com.google.gson
    // 美团多渠道
    implementation('com.meituan.android.walle:library:1.1.7')
//    implementation 'com.mhy:appupdate:1.5.0' //local
//    implementation 'com.gitee.mahongyin:appupdate-aar:1.5.0'
    implementation project(":appupdate")
}