plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

android {
    namespace 'com.github.sisong'
    compileSdk 34

    defaultConfig {
        minSdk 16

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    //artifactory加了这个就传上去了
    publishing {
        singleVariant("release") {
            //使用apg插件里的？会包含源码和文档
//            withSourcesJar()
//            withJavadocJar()
        }
    }
}

dependencies {

}
def GROUP_ID = 'com.mhy'
def ARTIFACT_ID = "hdpatch_ext_so"//project.getName()
def VERSION_NAME = '0.0.1'

//源码打包aar的task
//task androidSourcesJar(type: Jar) {
tasks.register('androidSourcesJar', Jar) {
    archiveClassifier.set("sources")
    // 源码路径，包含Java、kotlin代码
//    from android.sourceSets.main.java.srcDirs
//    exclude "**/R.class"
//    exclude "**/BuildConfig.class"
    from android.sourceSets.main.jniLibs.srcDirs
}
//jitpack
afterEvaluate {
    publishing {
        publications {
            register(MavenPublication) {
                from components.release
                //这里头是artifacts的配置信息，不填会采用默认的
                groupId = GROUP_ID
                artifactId = ARTIFACT_ID
                version = VERSION_NAME
                // 增加上传源码的 task
                artifact androidSourcesJar
                // 必须有这个 否则不会上传AAR包  将bundleReleaseAar任务的单个输出文件作为发布的AAR文件。这样，该AAR文件就会成为 MavenPublication 的 artifact 并进行发布
            }
        }
    }
}